name: Scan with Coverity

on:
  push:
    branches: ["master"]

jobs:
  scan:
    name: Scan Project with Coverity
    runs-on: ubuntu-latest
    container:
      image: jfitzpat/cov-thin-client:2022.12.0

    steps:
      - uses: actions/checkout@v3
      - name: scan
        run: coverity scan
