name: Scan Pull Request with Coverity

on: [pull_request]

jobs:
  scan:
    name: Scan Project Pull Request with Coverity
    runs-on: ubuntu-latest
    container:
      image: jfitzpat/cov-thin-client:2022.12.0

    steps:
      - uses: actions/checkout@v3
      - name: scan
        shell: bash
        env:
          COVERITY_CLI_CONNECT_USERNAME: ${{ secrets.COVERITY_CLI_CONNECT_USERNAME }}
          COVERITY_CLI_CONNECT_PASSWORD: ${{ secrets.COVERITY_CLI_CONNECT_PASSWORD }}
        run: |
          coverity scan -o commit.connect.comparison-report=comparison-report.json
          cat comparison-report.json | jq '.issues | [.[] | .["file"] = .strippedMainEventFilePathname | .["line"] = .mainEventLineNumber | .["title"] = .issueTypeDescription | .["message"] = .mainEventDescription | .["raw_details"] = .localEffect |  del(.strippedMainEventFilePathname, .mainEventLineNumber, .issueTypeDescription, .mainEventDescription, .mergeKey, .mainEventColumnNumber, .cweCategory, .presentInReferenceSnapshot, .classification, .localEffect, .impact) ]' > annotations.json
      - name: annotate
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.ANNOTATE_PR_TOKEN }}"
          title: Coverity Issues
          input: ./annotations.json
